otpFeatures:
  emission: true
  empiricalDelay: true
  gbfsGeofencingBuildTime: false
journeyPlanner:
  enabled: false
cronjobRedeployGraphBuilder:
    enabled: true
    mardukBucket: marduk-production
    mardukInternalBucket: ror-marduk-internal-production
    ignoreFareFrame: false
