otpFeatures:
  emission: true
  empiricalDelay: true
  gbfsGeofencingBuildTime: true
journeyPlanner:
  enabled: false
cronjobRedeployGraphBuilder:
    enabled: true
    mardukBucket: marduk-dev
    mardukInternalBucket: ror-marduk-internal-dev
    ignoreFareFrame: false
