otpFeatures:
  emission: true
  empiricalDelay: true
journeyPlanner:
  enabled: false
cronjobRedeployGraphBuilder:
    enabled: true
    mardukBucket: marduk-test
    mardukInternalBucket: ror-marduk-internal-test
    ignoreFareFrame: false