name: Process dev-1.x push or pr
on:
  push:
    branches:
      - dev-1.x
  pull_request:
    branches:
      - dev-1.x
jobs:
  docker-push:
    if: github.ref == 'refs/heads/dev-1.x'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image from dev-1.x and push it
        run: ./.github/workflows/scripts/build_and_push_dev.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
